version: '3.9'

services:
  app:
    container_name: app
    build: .
    restart: 'always'
    ports:
      - "$PORT:3000"
    stdin_open: true
    tty: true
    #trocar MYSQL_HOST(localHost - db) e MYSQL_USER (root - admin) no dotEnv
    environment:
     - MYSQL_HOST=$MYSQL_HOST
     - MYSQL_USER=$MYSQL_USER
     - MYSQL_PASSWORD=$MYSQL_PASSWORD
     - MYSQL_DATABASE=$MYSQL_DATABASE
    depends_on:
      - db
    volumes:
      - .:/usr/app
    networks:
      - conectionDB

  db:
    container_name: db
    image: mysql
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "$DB_PORT:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    networks:
      - conectionDB
    cap_add:
     - SYS_NICE
    volumes:
      - ./database:/usr/db
      - ./database/migrations/:/docker-entrypoint-initdb.d
    
networks:
  conectionDB:
    name: conectionDB   